name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify your Node.js version

      - name: Install dependencies
        run: npm ci # or npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          # To run tests headlessly, ensure your cypress.config.js is set up for headless runs
          # or specify headless mode here if the action supports it directly.
          # By default, cypress-io/github-action runs tests headlessly.
          # You can specify a browser:
          # browser: chrome
          # Or run specific specs:
          # spec: cypress/e2e/features/*.feature
          command: npm run cypress:run # Optional: if you have a specific script in package.json
        env:
          # If you need to set environment variables for your tests
          # CYPRESS_BASE_URL: http://localhost:3000 
          # Or any other CYPRESS_* variables
          # For example, if your application needs to be started first:
          # START_SERVER_COMMAND: npm start
          # WAIT_ON_URL: http://localhost:3000
          # WAIT_ON_TIMEOUT: 120
          DEBUG: 'cypress:*','cypress-cucumber-preprocessor' # Optional: for more verbose logs

      # Optional: Upload test artifacts (screenshots, videos)
      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v4
        if: failure() # Only upload if tests fail
        with:
          name: cypress-artifacts
          path: cypress/screenshots
          retention-days: 7
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always() # Always upload videos
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 7
      - name: Upload Cypress reports (if you generate them)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-reports
          path: cypress/reports # Adjust path if your reports are elsewhere
          retention-days: 7
